// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUItesting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// surseeleukerbad - Verwenden Sie "surseeleukerbadParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void surseeleukerbad()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinText uIBittegebenSieIhreEndText = this.UITransportAppWindow.UIBittegebenSieIhreEndWindow.UIBittegebenSieIhreEndText;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinButton uISchliessenButton = this.UITransportAppWindow.UISchliessenWindow.UISchliessenButton;
            #endregion

            // "Sursee" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.surseeleukerbadParams.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(24, 15));

            // "Sursee" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.SelectedItem = this.surseeleukerbadParams.UICb_startComboBoxSelectedItem;

            // Klicken "Bitte geben Sie Ihre Endstation ein:" Bezeichnung
            Mouse.Click(uIBittegebenSieIhreEndText, new Point(135, 7));

            // "Leukerbad" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.surseeleukerbadParams.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(168, 88));

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(168, 88));

            // "Leukerba" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.surseeleukerbadParams.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(48, 10));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(104, 10));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(119, 8));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(228, 201));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(228, 201));

            // Klicken "Schliessen" Schaltfläche
            Mouse.Click(uISchliessenButton, new Point(52, 18));
        }
        
        /// <summary>
        /// RecordedMethod1 - Verwenden Sie "RecordedMethod1Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            WinButton uISchliessenButton = this.UITransportAppWindow.UISchliessenWindow.UISchliessenButton;
            #endregion

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(47, 6));

            // "abb" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(30, 10));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(146, 17));

            // Doppelklicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.DoubleClick(uIZumStationenFahrplanButton, new Point(139, 8));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(139, 7));

            // Klicken "Schliessen" Schaltfläche
            Mouse.Click(uISchliessenButton, new Point(47, 16));
        }
        
        /// <summary>
        /// huobobermattstrasse - Verwenden Sie "huobobermattstrasseParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void huobobermattstrasse()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            #endregion

            // "Huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.huobobermattstrasseParams.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(26, 7));

            // "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.huobobermattstrasseParams.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(32, 14));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(125, 23));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(155, 18));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));
        }
        
        /// <summary>
        /// huobobermattstrasse2 - Verwenden Sie "huobobermattstrasse2Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void huobobermattstrasse2()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            WinCustom uIItemCustom = this.UICodedUITestsdoVisualWindow.UIItemGroup.UIItemCustom;
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            #endregion

            // "Huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.huobobermattstrasse2Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(26, 7));

            // "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.huobobermattstrasse2Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(32, 14));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(125, 23));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(155, 18));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(154, 3));

            // Klicken Benutzerdefiniertes Steuerelement
            Mouse.Click(uIItemCustom, new Point(534, 120));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.huobobermattstrasse2Params.UICb_startComboBoxEditableItem1;

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(313, 58));

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(41, 12));

            // "kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.huobobermattstrasse2Params.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(26, 9));

            // "Schaffhausen, Kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.huobobermattstrasse2Params.UIBittegebenSieIhreStaComboBoxSelectedItem;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(73, 24));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(133, 9));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(226, 197));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(141, 4));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(242, 198));
        }
        
        #region Properties
        public virtual surseeleukerbadParams surseeleukerbadParams
        {
            get
            {
                if ((this.msurseeleukerbadParams == null))
                {
                    this.msurseeleukerbadParams = new surseeleukerbadParams();
                }
                return this.msurseeleukerbadParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual huobobermattstrasseParams huobobermattstrasseParams
        {
            get
            {
                if ((this.mhuobobermattstrasseParams == null))
                {
                    this.mhuobobermattstrasseParams = new huobobermattstrasseParams();
                }
                return this.mhuobobermattstrasseParams;
            }
        }
        
        public virtual huobobermattstrasse2Params huobobermattstrasse2Params
        {
            get
            {
                if ((this.mhuobobermattstrasse2Params == null))
                {
                    this.mhuobobermattstrasse2Params = new huobobermattstrasse2Params();
                }
                return this.mhuobobermattstrasse2Params;
            }
        }
        
        public UITransportAppWindow UITransportAppWindow
        {
            get
            {
                if ((this.mUITransportAppWindow == null))
                {
                    this.mUITransportAppWindow = new UITransportAppWindow();
                }
                return this.mUITransportAppWindow;
            }
        }
        
        public UICodedUITestsdoVisualWindow UICodedUITestsdoVisualWindow
        {
            get
            {
                if ((this.mUICodedUITestsdoVisualWindow == null))
                {
                    this.mUICodedUITestsdoVisualWindow = new UICodedUITestsdoVisualWindow();
                }
                return this.mUICodedUITestsdoVisualWindow;
            }
        }
        #endregion
        
        #region Fields
        private surseeleukerbadParams msurseeleukerbadParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private huobobermattstrasseParams mhuobobermattstrasseParams;
        
        private huobobermattstrasse2Params mhuobobermattstrasse2Params;
        
        private UITransportAppWindow mUITransportAppWindow;
        
        private UICodedUITestsdoVisualWindow mUICodedUITestsdoVisualWindow;
        #endregion
    }
    
    /// <summary>
    /// An "surseeleukerbad" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class surseeleukerbadParams
    {
        
        #region Fields
        /// <summary>
        /// "Sursee" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "Sursee";
        
        /// <summary>
        /// "Sursee" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxSelectedItem = "Sursee";
        
        /// <summary>
        /// "Leukerbad" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "Leukerbad";
        
        /// <summary>
        /// "Leukerba" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "Leukerba";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "abb" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "abb";
        #endregion
    }
    
    /// <summary>
    /// An "huobobermattstrasse" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class huobobermattstrasseParams
    {
        
        #region Fields
        /// <summary>
        /// "Huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "Huob";
        
        /// <summary>
        /// "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "obermattstrasse";
        #endregion
    }
    
    /// <summary>
    /// An "huobobermattstrasse2" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class huobobermattstrasse2Params
    {
        
        #region Fields
        /// <summary>
        /// "Huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "Huob";
        
        /// <summary>
        /// "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "obermattstrasse";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem1 = "huob";
        
        /// <summary>
        /// "kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "kreuz";
        
        /// <summary>
        /// "Schaffhausen, Kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem = "Schaffhausen, Kreuz";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppWindow : WinWindow
    {
        
        public UITransportAppWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transport App";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public UICb_startWindow UICb_startWindow
        {
            get
            {
                if ((this.mUICb_startWindow == null))
                {
                    this.mUICb_startWindow = new UICb_startWindow(this);
                }
                return this.mUICb_startWindow;
            }
        }
        
        public UIStationsuchenWindow UIStationsuchenWindow
        {
            get
            {
                if ((this.mUIStationsuchenWindow == null))
                {
                    this.mUIStationsuchenWindow = new UIStationsuchenWindow(this);
                }
                return this.mUIStationsuchenWindow;
            }
        }
        
        public UIBittegebenSieIhreEndWindow UIBittegebenSieIhreEndWindow
        {
            get
            {
                if ((this.mUIBittegebenSieIhreEndWindow == null))
                {
                    this.mUIBittegebenSieIhreEndWindow = new UIBittegebenSieIhreEndWindow(this);
                }
                return this.mUIBittegebenSieIhreEndWindow;
            }
        }
        
        public UICb_endWindow UICb_endWindow
        {
            get
            {
                if ((this.mUICb_endWindow == null))
                {
                    this.mUICb_endWindow = new UICb_endWindow(this);
                }
                return this.mUICb_endWindow;
            }
        }
        
        public UITransportAppClient UITransportAppClient
        {
            get
            {
                if ((this.mUITransportAppClient == null))
                {
                    this.mUITransportAppClient = new UITransportAppClient(this);
                }
                return this.mUITransportAppClient;
            }
        }
        
        public UIStationsuchenWindow1 UIStationsuchenWindow1
        {
            get
            {
                if ((this.mUIStationsuchenWindow1 == null))
                {
                    this.mUIStationsuchenWindow1 = new UIStationsuchenWindow1(this);
                }
                return this.mUIStationsuchenWindow1;
            }
        }
        
        public UIVerbindungsuchenWindow UIVerbindungsuchenWindow
        {
            get
            {
                if ((this.mUIVerbindungsuchenWindow == null))
                {
                    this.mUIVerbindungsuchenWindow = new UIVerbindungsuchenWindow(this);
                }
                return this.mUIVerbindungsuchenWindow;
            }
        }
        
        public UIZumStationenFahrplanWindow UIZumStationenFahrplanWindow
        {
            get
            {
                if ((this.mUIZumStationenFahrplanWindow == null))
                {
                    this.mUIZumStationenFahrplanWindow = new UIZumStationenFahrplanWindow(this);
                }
                return this.mUIZumStationenFahrplanWindow;
            }
        }
        
        public UISchliessenWindow UISchliessenWindow
        {
            get
            {
                if ((this.mUISchliessenWindow == null))
                {
                    this.mUISchliessenWindow = new UISchliessenWindow(this);
                }
                return this.mUISchliessenWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICb_startWindow mUICb_startWindow;
        
        private UIStationsuchenWindow mUIStationsuchenWindow;
        
        private UIBittegebenSieIhreEndWindow mUIBittegebenSieIhreEndWindow;
        
        private UICb_endWindow mUICb_endWindow;
        
        private UITransportAppClient mUITransportAppClient;
        
        private UIStationsuchenWindow1 mUIStationsuchenWindow1;
        
        private UIVerbindungsuchenWindow mUIVerbindungsuchenWindow;
        
        private UIZumStationenFahrplanWindow mUIZumStationenFahrplanWindow;
        
        private UISchliessenWindow mUISchliessenWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_startWindow : WinWindow
    {
        
        public UICb_startWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_start";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_startComboBox
        {
            get
            {
                if ((this.mUICb_startComboBox == null))
                {
                    this.mUICb_startComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUICb_startComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUICb_startComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_startComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow : WinWindow
    {
        
        public UIStationsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchststation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIBittegebenSieIhreEndWindow : WinWindow
    {
        
        public UIBittegebenSieIhreEndWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "lbl_Endstation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinText UIBittegebenSieIhreEndText
        {
            get
            {
                if ((this.mUIBittegebenSieIhreEndText == null))
                {
                    this.mUIBittegebenSieIhreEndText = new WinText(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreEndText.SearchProperties[WinText.PropertyNames.Name] = "Bitte geben Sie Ihre Endstation ein:";
                    this.mUIBittegebenSieIhreEndText.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreEndText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIBittegebenSieIhreEndText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_endWindow : WinWindow
    {
        
        public UICb_endWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_end";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBittegebenSieIhreStaComboBox
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBittegebenSieIhreStaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppClient : WinClient
    {
        
        public UITransportAppClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Transport App";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinWindow UIBittegebenSieIhreStaWindow
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaWindow == null))
                {
                    this.mUIBittegebenSieIhreStaWindow = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.STATIC", PropertyExpressionOperator.Contains));
                    this.mUIBittegebenSieIhreStaWindow.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIBittegebenSieIhreStaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow1 : WinWindow
    {
        
        public UIStationsuchenWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchenstation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIVerbindungsuchenWindow : WinWindow
    {
        
        public UIVerbindungsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_VerbindungSuchen";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIVerbindungsuchenButton
        {
            get
            {
                if ((this.mUIVerbindungsuchenButton == null))
                {
                    this.mUIVerbindungsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIVerbindungsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Verbindung suchen";
                    this.mUIVerbindungsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIVerbindungsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIVerbindungsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIZumStationenFahrplanWindow : WinWindow
    {
        
        public UIZumStationenFahrplanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_fahrplan";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIZumStationenFahrplanButton
        {
            get
            {
                if ((this.mUIZumStationenFahrplanButton == null))
                {
                    this.mUIZumStationenFahrplanButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIZumStationenFahrplanButton.SearchProperties[WinButton.PropertyNames.Name] = "Zum Stationen Fahrplan";
                    this.mUIZumStationenFahrplanButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIZumStationenFahrplanButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIZumStationenFahrplanButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISchliessenWindow : WinWindow
    {
        
        public UISchliessenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_close";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UISchliessenButton
        {
            get
            {
                if ((this.mUISchliessenButton == null))
                {
                    this.mUISchliessenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISchliessenButton.SearchProperties[WinButton.PropertyNames.Name] = "Schliessen";
                    this.mUISchliessenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUISchliessenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISchliessenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICodedUITestsdoVisualWindow : WinWindow
    {
        
        public UICodedUITestsdoVisualWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Coded UI Tests do Visual Studio 2017 - YouTube - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Coded UI Tests do Visual Studio 2017 - YouTube - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("Coded UI Tests do Visual Studio 2017 - YouTube - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Suchkriterien
                    this.mUIItemCustom.WindowTitles.Add("Coded UI Tests do Visual Studio 2017 - YouTube - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
}
