// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject3
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Verwenden Sie "RecordedMethod1Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinWindow uIItemWindow = this.UITransportAppWindow.UITransportAppClient.UIItemWindow;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinEdit uIItemEdit = this.UITransportAppWindow.UIItemWindow.UIItemEdit;
            WinWindow uIDtp_datum_verbindungWindow = this.UITransportAppWindow.UITransportAppClient.UIDtp_datum_verbindungWindow;
            #endregion

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(102, 16));

            // Klicken "▼▲" Fenster
            Mouse.Click(uIItemWindow, new Point(136, 61));

            // "luzernerhof" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(206, 65));

            // Klicken "dtp_datum_verbindung" Fenster
            Mouse.Click(uIDtp_datum_verbindungWindow, new Point(145, 87));

            // Klicken "dtp_datum_verbindung" Fenster
            Mouse.Click(uIDtp_datum_verbindungWindow, new Point(141, 79));
        }
        
        /// <summary>
        /// RecordedMethod2 - Verwenden Sie "RecordedMethod2Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinWindow uIItemWindow = this.UITransportAppWindow.UITransportAppClient.UIItemWindow;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinEdit uIItemEdit = this.UITransportAppWindow.UIItemWindow.UIItemEdit;
            WinWindow uIDtp_datum_verbindungWindow = this.UITransportAppWindow.UITransportAppClient.UIDtp_datum_verbindungWindow;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            #endregion

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod2Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(102, 16));

            // Klicken "▼▲" Fenster
            Mouse.Click(uIItemWindow, new Point(136, 61));

            // "luzernerhof" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod2Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(206, 65));

            // Klicken "dtp_datum_verbindung" Fenster
            Mouse.Click(uIDtp_datum_verbindungWindow, new Point(145, 87));

            // Klicken "dtp_datum_verbindung" Fenster
            Mouse.Click(uIDtp_datum_verbindungWindow, new Point(141, 79));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod2Params.UICb_startComboBoxEditableItem1;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(57, 5));

            // Klicken "▼▲" Fenster
            Mouse.Click(uIItemWindow, new Point(163, 74));

            // "schwanenplatz" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod2Params.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(230, 58));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(120, 13));
        }
        
        /// <summary>
        /// RecordedMethod3 - Verwenden Sie "RecordedMethod3Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WinTreeItem uIWindowsCTreeItem = this.UITransportapiWindow.UIStrukturansichtWindow.UIDesktopTreeItem.UIDieserPCTreeItem.UIWindowsCTreeItem;
            WinEdit uINameEdit = this.UITransportapiWindow.UIItemWindow.UIProgrammex86ListItem.UINameEdit;
            WinEdit uINameEdit1 = this.UITransportapiWindow.UIItemWindow1.UIJoëlTheilerListItem.UINameEdit;
            WinEdit uINameEdit2 = this.UITransportapiWindow.UIItemWindow2.UISetupSBBAPPListItem.UINameEdit;
            WinEdit uINameEdit3 = this.UITransportapiWindow.UIItemWindow3.UISwissTransportGUIexeListItem.UINameEdit;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinWindow uIItemWindow1 = this.UITransportAppWindow.UITransportAppClient.UIItemWindow1;
            WinComboBox uIBittegebenSieIhreStaComboBox1 = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox1;
            WinEdit uIItemEdit = this.UITransportAppWindow.UIItemWindow.UIItemEdit;
            WinWindow uIItemWindow2 = this.UITransportAppWindow.UITransportAppClient.UIItemWindow2;
            WinWindow uIButton1Window = this.UITransportAppWindow.UITransportAppClient.UIButton1Window;
            #endregion

            // Klicken "Desktop" -> "Dieser PC" -> "Windows (C:)" Baumelement
            Mouse.Click(uIWindowsCTreeItem, new Point(18, 18));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(52, 9));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit1, new Point(137, 12));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit2, new Point(137, 12));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit3, new Point(105, 18));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod3Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(17, 5));

            // Klicken "▲▼" Fenster
            Mouse.Click(uIItemWindow1, new Point(169, 69));

            // "schlössli" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox1.EditableItem = this.RecordedMethod3Params.UIBittegebenSieIhreStaComboBox1EditableItem;

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(218, 66));

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(168, 68));

            // Klicken "▲▼" Fenster
            Mouse.Click(uIItemWindow2, new Point(151, 98));

            // Klicken "button1" Fenster
            Mouse.Click(uIButton1Window, new Point(145, 90));
        }
        
        /// <summary>
        /// AssertMethod1 - Verwenden Sie "AssertMethod1ExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinTable uIDataGridViewTable = this.UITransportAppWindow.UIDgV_VerbindungenWindow.UIDataGridViewTable;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'ControlType' von "DataGridView" Tabelle ist gleich 'Table'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIDataGridViewTableControlType, uIDataGridViewTable.ControlType.ToString());
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public UITransportAppWindow UITransportAppWindow
        {
            get
            {
                if ((this.mUITransportAppWindow == null))
                {
                    this.mUITransportAppWindow = new UITransportAppWindow();
                }
                return this.mUITransportAppWindow;
            }
        }
        
        public UITransportapiWindow UITransportapiWindow
        {
            get
            {
                if ((this.mUITransportapiWindow == null))
                {
                    this.mUITransportapiWindow = new UITransportapiWindow();
                }
                return this.mUITransportapiWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private UITransportAppWindow mUITransportAppWindow;
        
        private UITransportapiWindow mUITransportapiWindow;
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "luzernerhof" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "luzernerhof";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod2" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "luzernerhof" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "luzernerhof";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem1 = "huob";
        
        /// <summary>
        /// "schwanenplatz" in "Bitte geben Sie Ihre Startstation ein" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "schwanenplatz";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod3" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "schlössli" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBox1EditableItem = "schlössli";
        #endregion
    }
    
    /// <summary>
    /// An "AssertMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'ControlType' von "DataGridView" Tabelle ist gleich 'Table'
        /// </summary>
        public string UIDataGridViewTableControlType = "Table";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppWindow : WinWindow
    {
        
        public UITransportAppWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transport App";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public UICb_startWindow UICb_startWindow
        {
            get
            {
                if ((this.mUICb_startWindow == null))
                {
                    this.mUICb_startWindow = new UICb_startWindow(this);
                }
                return this.mUICb_startWindow;
            }
        }
        
        public UIStationsuchenWindow UIStationsuchenWindow
        {
            get
            {
                if ((this.mUIStationsuchenWindow == null))
                {
                    this.mUIStationsuchenWindow = new UIStationsuchenWindow(this);
                }
                return this.mUIStationsuchenWindow;
            }
        }
        
        public UITransportAppClient UITransportAppClient
        {
            get
            {
                if ((this.mUITransportAppClient == null))
                {
                    this.mUITransportAppClient = new UITransportAppClient(this);
                }
                return this.mUITransportAppClient;
            }
        }
        
        public UICb_endWindow UICb_endWindow
        {
            get
            {
                if ((this.mUICb_endWindow == null))
                {
                    this.mUICb_endWindow = new UICb_endWindow(this);
                }
                return this.mUICb_endWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIVerbindungsuchenWindow UIVerbindungsuchenWindow
        {
            get
            {
                if ((this.mUIVerbindungsuchenWindow == null))
                {
                    this.mUIVerbindungsuchenWindow = new UIVerbindungsuchenWindow(this);
                }
                return this.mUIVerbindungsuchenWindow;
            }
        }
        
        public UIDgV_VerbindungenWindow UIDgV_VerbindungenWindow
        {
            get
            {
                if ((this.mUIDgV_VerbindungenWindow == null))
                {
                    this.mUIDgV_VerbindungenWindow = new UIDgV_VerbindungenWindow(this);
                }
                return this.mUIDgV_VerbindungenWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICb_startWindow mUICb_startWindow;
        
        private UIStationsuchenWindow mUIStationsuchenWindow;
        
        private UITransportAppClient mUITransportAppClient;
        
        private UICb_endWindow mUICb_endWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIVerbindungsuchenWindow mUIVerbindungsuchenWindow;
        
        private UIDgV_VerbindungenWindow mUIDgV_VerbindungenWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_startWindow : WinWindow
    {
        
        public UICb_startWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_start";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_startComboBox
        {
            get
            {
                if ((this.mUICb_startComboBox == null))
                {
                    this.mUICb_startComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUICb_startComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUICb_startComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_startComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow : WinWindow
    {
        
        public UIStationsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchststation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppClient : WinClient
    {
        
        public UITransportAppClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Transport App";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIItemWindow.SearchProperties[WinWindow.PropertyNames.Name] = "▼▲";
                    this.mUIItemWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIItemWindow.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIItemWindow;
            }
        }
        
        public WinWindow UIDtp_datum_verbindungWindow
        {
            get
            {
                if ((this.mUIDtp_datum_verbindungWindow == null))
                {
                    this.mUIDtp_datum_verbindungWindow = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIDtp_datum_verbindungWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Dienstag, 24. April 2018";
                    this.mUIDtp_datum_verbindungWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.SysDateTimePick32", PropertyExpressionOperator.Contains));
                    this.mUIDtp_datum_verbindungWindow.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIDtp_datum_verbindungWindow;
            }
        }
        
        public WinWindow UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIItemWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "▲▼";
                    this.mUIItemWindow1.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIItemWindow1.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIItemWindow1;
            }
        }
        
        public WinWindow UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIItemWindow2.SearchProperties[WinWindow.PropertyNames.Name] = "▲▼";
                    this.mUIItemWindow2.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIItemWindow2.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIItemWindow2;
            }
        }
        
        public WinWindow UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIButton1Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIButton1Window.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIButton1Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItemWindow;
        
        private WinWindow mUIDtp_datum_verbindungWindow;
        
        private WinWindow mUIItemWindow1;
        
        private WinWindow mUIItemWindow2;
        
        private WinWindow mUIButton1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_endWindow : WinWindow
    {
        
        public UICb_endWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_end";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBittegebenSieIhreStaComboBox
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein";
                    this.mUIBittegebenSieIhreStaComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox;
            }
        }
        
        public WinComboBox UIBittegebenSieIhreStaComboBox1
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox1 == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox1 = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox1.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaComboBox1.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox1;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBittegebenSieIhreStaComboBox;
        
        private WinComboBox mUIBittegebenSieIhreStaComboBox1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUIItemEdit.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIVerbindungsuchenWindow : WinWindow
    {
        
        public UIVerbindungsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_VerbindungSuchen";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIVerbindungsuchenButton
        {
            get
            {
                if ((this.mUIVerbindungsuchenButton == null))
                {
                    this.mUIVerbindungsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIVerbindungsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Verbindung suchen";
                    this.mUIVerbindungsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIVerbindungsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIVerbindungsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDgV_VerbindungenWindow : WinWindow
    {
        
        public UIDgV_VerbindungenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgV_Verbindungen";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new WinTable(this);
                    #region Suchkriterien
                    this.mUIDataGridViewTable.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
                    this.mUIDataGridViewTable.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private WinTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportapiWindow : WinWindow
    {
        
        public UITransportapiWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transportapi";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Transportapi");
            this.WindowTitles.Add("Windows (C:)");
            this.WindowTitles.Add("Programme (x86)");
            this.WindowTitles.Add("Joël Theiler");
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public UIStrukturansichtWindow UIStrukturansichtWindow
        {
            get
            {
                if ((this.mUIStrukturansichtWindow == null))
                {
                    this.mUIStrukturansichtWindow = new UIStrukturansichtWindow(this);
                }
                return this.mUIStrukturansichtWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        #endregion
        
        #region Fields
        private UIStrukturansichtWindow mUIStrukturansichtWindow;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow3 mUIItemWindow3;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStrukturansichtWindow : WinWindow
    {
        
        public UIStrukturansichtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("Transportapi");
            #endregion
        }
        
        #region Properties
        public UIDesktopTreeItem UIDesktopTreeItem
        {
            get
            {
                if ((this.mUIDesktopTreeItem == null))
                {
                    this.mUIDesktopTreeItem = new UIDesktopTreeItem(this);
                }
                return this.mUIDesktopTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIDesktopTreeItem mUIDesktopTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDesktopTreeItem : WinTreeItem
    {
        
        public UIDesktopTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Desktop";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("Transportapi");
            #endregion
        }
        
        #region Properties
        public UIDieserPCTreeItem UIDieserPCTreeItem
        {
            get
            {
                if ((this.mUIDieserPCTreeItem == null))
                {
                    this.mUIDieserPCTreeItem = new UIDieserPCTreeItem(this);
                }
                return this.mUIDieserPCTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIDieserPCTreeItem mUIDieserPCTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDieserPCTreeItem : WinTreeItem
    {
        
        public UIDieserPCTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Dieser PC";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("Transportapi");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIWindowsCTreeItem
        {
            get
            {
                if ((this.mUIWindowsCTreeItem == null))
                {
                    this.mUIWindowsCTreeItem = new WinTreeItem(this);
                    #region Suchkriterien
                    this.mUIWindowsCTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Windows (C:)";
                    this.mUIWindowsCTreeItem.SearchProperties["Value"] = "2";
                    this.mUIWindowsCTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIWindowsCTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIWindowsCTreeItem.WindowTitles.Add("Transportapi");
                    #endregion
                }
                return this.mUIWindowsCTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIWindowsCTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Windows (C:)");
            #endregion
        }
        
        #region Properties
        public UIProgrammex86ListItem UIProgrammex86ListItem
        {
            get
            {
                if ((this.mUIProgrammex86ListItem == null))
                {
                    this.mUIProgrammex86ListItem = new UIProgrammex86ListItem(this);
                }
                return this.mUIProgrammex86ListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIProgrammex86ListItem mUIProgrammex86ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIProgrammex86ListItem : WinListItem
    {
        
        public UIProgrammex86ListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Programme (x86)";
            this.WindowTitles.Add("Windows (C:)");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Windows (C:)");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Programme (x86)");
            #endregion
        }
        
        #region Properties
        public UIJoëlTheilerListItem UIJoëlTheilerListItem
        {
            get
            {
                if ((this.mUIJoëlTheilerListItem == null))
                {
                    this.mUIJoëlTheilerListItem = new UIJoëlTheilerListItem(this);
                }
                return this.mUIJoëlTheilerListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIJoëlTheilerListItem mUIJoëlTheilerListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIJoëlTheilerListItem : WinListItem
    {
        
        public UIJoëlTheilerListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Joël Theiler";
            this.WindowTitles.Add("Programme (x86)");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Programme (x86)");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Joël Theiler");
            #endregion
        }
        
        #region Properties
        public UISetupSBBAPPListItem UISetupSBBAPPListItem
        {
            get
            {
                if ((this.mUISetupSBBAPPListItem == null))
                {
                    this.mUISetupSBBAPPListItem = new UISetupSBBAPPListItem(this);
                }
                return this.mUISetupSBBAPPListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISetupSBBAPPListItem mUISetupSBBAPPListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISetupSBBAPPListItem : WinListItem
    {
        
        public UISetupSBBAPPListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SetupSBBAPP";
            this.WindowTitles.Add("Joël Theiler");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Joël Theiler");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public UISwissTransportGUIexeListItem UISwissTransportGUIexeListItem
        {
            get
            {
                if ((this.mUISwissTransportGUIexeListItem == null))
                {
                    this.mUISwissTransportGUIexeListItem = new UISwissTransportGUIexeListItem(this);
                }
                return this.mUISwissTransportGUIexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISwissTransportGUIexeListItem mUISwissTransportGUIexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISwissTransportGUIexeListItem : WinListItem
    {
        
        public UISwissTransportGUIexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SwissTransportGUI.exe";
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("SetupSBBAPP");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
}
