// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Meggen24 - Verwenden Sie "Meggen24Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Meggen24()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            WinTitleBar uIItemTitleBar = this.UIItemWindow.UIItemWindow1.UIItemTitleBar;
            #endregion

            // "Huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.Meggen24Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(18, 17));

            // "Obermatts" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.Meggen24Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(28, 11));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(107, 24));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(127, 5));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(134, 3));

            // Klicken Titelleiste
            Mouse.Click(uIItemTitleBar, new Point(-4, 5));
        }
        
        /// <summary>
        /// RecordedMethod1 - Verwenden Sie "RecordedMethod1Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinButton uIZumStationenFahrplanButton = this.UITransportAppWindow.UIZumStationenFahrplanWindow.UIZumStationenFahrplanButton;
            WinTitleBar uIItemTitleBar = this.UIItemWindow.UIItemWindow1.UIItemTitleBar;
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            #endregion

            // "Huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(18, 17));

            // "Obermatts" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(28, 11));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(107, 24));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(127, 5));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(134, 3));

            // Klicken Titelleiste
            Mouse.Click(uIItemTitleBar, new Point(-4, 5));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem1;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(70, 13));

            // "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(22, 18));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(144, 16));

            // Klicken "Zum Stationen Fahrplan" Schaltfläche
            Mouse.Click(uIZumStationenFahrplanButton, new Point(147, 3));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(254, 203));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(254, 203));
        }
        
        #region Properties
        public virtual Meggen24Params Meggen24Params
        {
            get
            {
                if ((this.mMeggen24Params == null))
                {
                    this.mMeggen24Params = new Meggen24Params();
                }
                return this.mMeggen24Params;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UITransportAppWindow UITransportAppWindow
        {
            get
            {
                if ((this.mUITransportAppWindow == null))
                {
                    this.mUITransportAppWindow = new UITransportAppWindow();
                }
                return this.mUITransportAppWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private Meggen24Params mMeggen24Params;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UITransportAppWindow mUITransportAppWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// An "Meggen24" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class Meggen24Params
    {
        
        #region Fields
        /// <summary>
        /// "Huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "Huob";
        
        /// <summary>
        /// "Obermatts" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "Obermatts";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// "Huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "Huob";
        
        /// <summary>
        /// "Obermatts" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "Obermatts";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem1 = "huob";
        
        /// <summary>
        /// "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "obermattstrasse";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppWindow : WinWindow
    {
        
        public UITransportAppWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transport App";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public UICb_startWindow UICb_startWindow
        {
            get
            {
                if ((this.mUICb_startWindow == null))
                {
                    this.mUICb_startWindow = new UICb_startWindow(this);
                }
                return this.mUICb_startWindow;
            }
        }
        
        public UIStationsuchenWindow UIStationsuchenWindow
        {
            get
            {
                if ((this.mUIStationsuchenWindow == null))
                {
                    this.mUIStationsuchenWindow = new UIStationsuchenWindow(this);
                }
                return this.mUIStationsuchenWindow;
            }
        }
        
        public UICb_endWindow UICb_endWindow
        {
            get
            {
                if ((this.mUICb_endWindow == null))
                {
                    this.mUICb_endWindow = new UICb_endWindow(this);
                }
                return this.mUICb_endWindow;
            }
        }
        
        public UIStationsuchenWindow1 UIStationsuchenWindow1
        {
            get
            {
                if ((this.mUIStationsuchenWindow1 == null))
                {
                    this.mUIStationsuchenWindow1 = new UIStationsuchenWindow1(this);
                }
                return this.mUIStationsuchenWindow1;
            }
        }
        
        public UIVerbindungsuchenWindow UIVerbindungsuchenWindow
        {
            get
            {
                if ((this.mUIVerbindungsuchenWindow == null))
                {
                    this.mUIVerbindungsuchenWindow = new UIVerbindungsuchenWindow(this);
                }
                return this.mUIVerbindungsuchenWindow;
            }
        }
        
        public UIZumStationenFahrplanWindow UIZumStationenFahrplanWindow
        {
            get
            {
                if ((this.mUIZumStationenFahrplanWindow == null))
                {
                    this.mUIZumStationenFahrplanWindow = new UIZumStationenFahrplanWindow(this);
                }
                return this.mUIZumStationenFahrplanWindow;
            }
        }
        
        public WinClient UITransportAppClient
        {
            get
            {
                if ((this.mUITransportAppClient == null))
                {
                    this.mUITransportAppClient = new WinClient(this);
                    #region Suchkriterien
                    this.mUITransportAppClient.SearchProperties[WinControl.PropertyNames.Name] = "Transport App";
                    this.mUITransportAppClient.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUITransportAppClient;
            }
        }
        #endregion
        
        #region Fields
        private UICb_startWindow mUICb_startWindow;
        
        private UIStationsuchenWindow mUIStationsuchenWindow;
        
        private UICb_endWindow mUICb_endWindow;
        
        private UIStationsuchenWindow1 mUIStationsuchenWindow1;
        
        private UIVerbindungsuchenWindow mUIVerbindungsuchenWindow;
        
        private UIZumStationenFahrplanWindow mUIZumStationenFahrplanWindow;
        
        private WinClient mUITransportAppClient;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_startWindow : WinWindow
    {
        
        public UICb_startWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_start";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_startComboBox
        {
            get
            {
                if ((this.mUICb_startComboBox == null))
                {
                    this.mUICb_startComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUICb_startComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUICb_startComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_startComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow : WinWindow
    {
        
        public UIStationsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchststation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_endWindow : WinWindow
    {
        
        public UICb_endWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_end";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBittegebenSieIhreStaComboBox
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBittegebenSieIhreStaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow1 : WinWindow
    {
        
        public UIStationsuchenWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchenstation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIVerbindungsuchenWindow : WinWindow
    {
        
        public UIVerbindungsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_VerbindungSuchen";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIVerbindungsuchenButton
        {
            get
            {
                if ((this.mUIVerbindungsuchenButton == null))
                {
                    this.mUIVerbindungsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIVerbindungsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Verbindung suchen";
                    this.mUIVerbindungsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIVerbindungsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIVerbindungsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIZumStationenFahrplanWindow : WinWindow
    {
        
        public UIZumStationenFahrplanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_fahrplan";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIZumStationenFahrplanButton
        {
            get
            {
                if ((this.mUIZumStationenFahrplanButton == null))
                {
                    this.mUIZumStationenFahrplanButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIZumStationenFahrplanButton.SearchProperties[WinButton.PropertyNames.Name] = "Zum Stationen Fahrplan";
                    this.mUIZumStationenFahrplanButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIZumStationenFahrplanButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIZumStationenFahrplanButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIItemTitleBar
        {
            get
            {
                if ((this.mUIItemTitleBar == null))
                {
                    this.mUIItemTitleBar = new WinTitleBar(this);
                }
                return this.mUIItemTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIItemTitleBar;
        #endregion
    }
}
