// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// bahnhofhuob - Verwenden Sie "bahnhofhuobParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void bahnhofhuob()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            #endregion

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.bahnhofhuobParams.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(47, 17));

            // "luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.bahnhofhuobParams.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(228, 84));

            // "Luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.bahnhofhuobParams.UIBittegebenSieIhreStaComboBoxSelectedItem;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(110, 5));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(117, 15));
        }
        
        /// <summary>
        /// RecordedMethod1 - Verwenden Sie "RecordedMethod1Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            #endregion

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(47, 17));

            // "luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(228, 84));

            // "Luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxSelectedItem;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(110, 5));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(117, 15));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem1;

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(338, 59));

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(60, 9));

            // "kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(326, 114));

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(243, 88));

            // "Schaffhausen, Kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxSelectedItem1;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(48, 19));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(96, 20));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod1Params.UICb_startComboBoxEditableItem2;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(20, 7));

            // "bahnhof luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod1Params.UIBittegebenSieIhreStaComboBoxEditableItem2;

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(318, 82));

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(39, 13));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(135, 18));
        }
        
        /// <summary>
        /// RecordedMethod2 - Verwenden Sie "RecordedMethod2Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            #endregion

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(148, 33));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod2Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(46, 3));

            // "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod2Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(80, 11));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(123, 26));
        }
        
        /// <summary>
        /// RecordedMethod3 - Verwenden Sie "RecordedMethod3Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinButton uIStationsuchenButton1 = this.UITransportAppWindow.UIStationsuchenWindow1.UIStationsuchenButton;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UISwissTransportGUIexeListItem.UINameEdit;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            #endregion

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(148, 33));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod3Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(46, 3));

            // "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod3Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Station such&en" Schaltfläche
            Mouse.Click(uIStationsuchenButton1, new Point(80, 11));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(123, 26));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(32, 11));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod3Params.UICb_startComboBoxEditableItem1;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(60, 4));

            // "kappelle" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod3Params.UIBittegebenSieIhreStaComboBoxEditableItem1;

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(207, 88));

            // "Masescha, Kappelle" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.RecordedMethod3Params.UIBittegebenSieIhreStaComboBoxSelectedItem;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(118, 14));
        }
        
        /// <summary>
        /// RecordedMethod4 - Verwenden Sie "RecordedMethod4Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            WinSplitButton uIÄnderungsdatumSplitButton = this.UIDebugWindow.UIItemWindow.UIKopfzeileList.UIÄnderungsdatumSplitButton;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            #endregion

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(201, 162));

            // Doppelklicken "Verbindung suchen" Schaltfläche
            Mouse.DoubleClick(uIVerbindungsuchenButton, new Point(102, 23));

            // Doppelklicken "Verbindung suchen" Schaltfläche
            Mouse.DoubleClick(uIVerbindungsuchenButton, new Point(104, 25));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(104, 25));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(121, 22));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(121, 22));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(266, 113));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(274, 101));

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(293, 113));

            // Klicken "Änderungsdatum" Unterteilte Schaltfläche
            Mouse.Click(uIÄnderungsdatumSplitButton, new Point(36, 13));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod4Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(40, 15));

            // "megg" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod4Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(222, 86));

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(135, 17));
        }
        
        /// <summary>
        /// RecordedMethod5 - Verwenden Sie "RecordedMethod5Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UISwissTransportGUIexeListItem.UINameEdit;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinClient uITransportAppClient = this.UITransportAppWindow.UITransportAppClient;
            WinWindow uIBittegebenSieIhreStaWindow = this.UITransportAppWindow.UITransportAppClient.UIBittegebenSieIhreStaWindow;
            WinButton uIVerbindungsuchenButton = this.UITransportAppWindow.UIVerbindungsuchenWindow.UIVerbindungsuchenButton;
            #endregion

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(89, 13));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.RecordedMethod5Params.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(77, 4));

            // "balm" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.RecordedMethod5Params.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken "Transport App" Client
            Mouse.Click(uITransportAppClient, new Point(316, 82));

            // Klicken "Bitte geben Sie Ihre Startstation ein:" Fenster
            Mouse.Click(uIBittegebenSieIhreStaWindow, new Point(222, 85));

            // "Meggen, Balm" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.SelectedItem = this.RecordedMethod5Params.UIBittegebenSieIhreStaComboBoxSelectedItem;

            // Klicken "Verbindung suchen" Schaltfläche
            Mouse.Click(uIVerbindungsuchenButton, new Point(94, 13));
        }
        
        /// <summary>
        /// valdiationcorrect - Verwenden Sie "valdiationcorrectExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void valdiationcorrect()
        {
            #region Variable Declarations
            WinText uIValidationcorrectText = this.UIValidationcorrectWindow.UIValidationcorrectText;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'Name' von "Validation correct" Bezeichnung ist gleich 'Validation correct'
            Assert.AreEqual(this.valdiationcorrectExpectedValues.UIValidationcorrectTextName, uIValidationcorrectText.Name);
        }
        
        #region Properties
        public virtual bahnhofhuobParams bahnhofhuobParams
        {
            get
            {
                if ((this.mbahnhofhuobParams == null))
                {
                    this.mbahnhofhuobParams = new bahnhofhuobParams();
                }
                return this.mbahnhofhuobParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }
        
        public virtual RecordedMethod5Params RecordedMethod5Params
        {
            get
            {
                if ((this.mRecordedMethod5Params == null))
                {
                    this.mRecordedMethod5Params = new RecordedMethod5Params();
                }
                return this.mRecordedMethod5Params;
            }
        }
        
        public virtual valdiationcorrectExpectedValues valdiationcorrectExpectedValues
        {
            get
            {
                if ((this.mvaldiationcorrectExpectedValues == null))
                {
                    this.mvaldiationcorrectExpectedValues = new valdiationcorrectExpectedValues();
                }
                return this.mvaldiationcorrectExpectedValues;
            }
        }
        
        public UITransportAppWindow UITransportAppWindow
        {
            get
            {
                if ((this.mUITransportAppWindow == null))
                {
                    this.mUITransportAppWindow = new UITransportAppWindow();
                }
                return this.mUITransportAppWindow;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIValidationcorrectWindow UIValidationcorrectWindow
        {
            get
            {
                if ((this.mUIValidationcorrectWindow == null))
                {
                    this.mUIValidationcorrectWindow = new UIValidationcorrectWindow();
                }
                return this.mUIValidationcorrectWindow;
            }
        }
        #endregion
        
        #region Fields
        private bahnhofhuobParams mbahnhofhuobParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private RecordedMethod4Params mRecordedMethod4Params;
        
        private RecordedMethod5Params mRecordedMethod5Params;
        
        private valdiationcorrectExpectedValues mvaldiationcorrectExpectedValues;
        
        private UITransportAppWindow mUITransportAppWindow;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIValidationcorrectWindow mUIValidationcorrectWindow;
        #endregion
    }
    
    /// <summary>
    /// An "bahnhofhuob" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class bahnhofhuobParams
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "luzern";
        
        /// <summary>
        /// "Luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem = "Luzern";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "luzern";
        
        /// <summary>
        /// "Luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem = "Luzern";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem1 = "huob";
        
        /// <summary>
        /// "kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "kreuz";
        
        /// <summary>
        /// "Schaffhausen, Kreuz" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem1 = "Schaffhausen, Kreuz";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem2 = "huob";
        
        /// <summary>
        /// "bahnhof luzern" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem2 = "bahnhof luzern";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod2" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "obermattstrasse";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod3" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "obermattstrasse" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "obermattstrasse";
        
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem1 = "huob";
        
        /// <summary>
        /// "kappelle" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem1 = "kappelle";
        
        /// <summary>
        /// "Masescha, Kappelle" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem = "Masescha, Kappelle";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod4" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod4Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "megg" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "megg";
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod5" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class RecordedMethod5Params
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "balm" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "balm";
        
        /// <summary>
        /// "Meggen, Balm" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxSelectedItem = "Meggen, Balm";
        #endregion
    }
    
    /// <summary>
    /// An "valdiationcorrect" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class valdiationcorrectExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'Name' von "Validation correct" Bezeichnung ist gleich 'Validation correct'
        /// </summary>
        public string UIValidationcorrectTextName = "Validation correct";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppWindow : WinWindow
    {
        
        public UITransportAppWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transport App";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public UICb_startWindow UICb_startWindow
        {
            get
            {
                if ((this.mUICb_startWindow == null))
                {
                    this.mUICb_startWindow = new UICb_startWindow(this);
                }
                return this.mUICb_startWindow;
            }
        }
        
        public UIStationsuchenWindow UIStationsuchenWindow
        {
            get
            {
                if ((this.mUIStationsuchenWindow == null))
                {
                    this.mUIStationsuchenWindow = new UIStationsuchenWindow(this);
                }
                return this.mUIStationsuchenWindow;
            }
        }
        
        public UICb_endWindow UICb_endWindow
        {
            get
            {
                if ((this.mUICb_endWindow == null))
                {
                    this.mUICb_endWindow = new UICb_endWindow(this);
                }
                return this.mUICb_endWindow;
            }
        }
        
        public UITransportAppClient UITransportAppClient
        {
            get
            {
                if ((this.mUITransportAppClient == null))
                {
                    this.mUITransportAppClient = new UITransportAppClient(this);
                }
                return this.mUITransportAppClient;
            }
        }
        
        public UIVerbindungsuchenWindow UIVerbindungsuchenWindow
        {
            get
            {
                if ((this.mUIVerbindungsuchenWindow == null))
                {
                    this.mUIVerbindungsuchenWindow = new UIVerbindungsuchenWindow(this);
                }
                return this.mUIVerbindungsuchenWindow;
            }
        }
        
        public UIStationsuchenWindow1 UIStationsuchenWindow1
        {
            get
            {
                if ((this.mUIStationsuchenWindow1 == null))
                {
                    this.mUIStationsuchenWindow1 = new UIStationsuchenWindow1(this);
                }
                return this.mUIStationsuchenWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UICb_startWindow mUICb_startWindow;
        
        private UIStationsuchenWindow mUIStationsuchenWindow;
        
        private UICb_endWindow mUICb_endWindow;
        
        private UITransportAppClient mUITransportAppClient;
        
        private UIVerbindungsuchenWindow mUIVerbindungsuchenWindow;
        
        private UIStationsuchenWindow1 mUIStationsuchenWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_startWindow : WinWindow
    {
        
        public UICb_startWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_start";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_startComboBox
        {
            get
            {
                if ((this.mUICb_startComboBox == null))
                {
                    this.mUICb_startComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUICb_startComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUICb_startComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_startComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow : WinWindow
    {
        
        public UIStationsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchststation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_endWindow : WinWindow
    {
        
        public UICb_endWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_end";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBittegebenSieIhreStaComboBox
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBittegebenSieIhreStaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppClient : WinClient
    {
        
        public UITransportAppClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Transport App";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinWindow UIBittegebenSieIhreStaWindow
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaWindow == null))
                {
                    this.mUIBittegebenSieIhreStaWindow = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.STATIC", PropertyExpressionOperator.Contains));
                    this.mUIBittegebenSieIhreStaWindow.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIBittegebenSieIhreStaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIVerbindungsuchenWindow : WinWindow
    {
        
        public UIVerbindungsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_VerbindungSuchen";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIVerbindungsuchenButton
        {
            get
            {
                if ((this.mUIVerbindungsuchenButton == null))
                {
                    this.mUIVerbindungsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIVerbindungsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Verbindung suchen";
                    this.mUIVerbindungsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIVerbindungsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIVerbindungsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow1 : WinWindow
    {
        
        public UIStationsuchenWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchenstation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UISwissTransportGUIexeListItem UISwissTransportGUIexeListItem
        {
            get
            {
                if ((this.mUISwissTransportGUIexeListItem == null))
                {
                    this.mUISwissTransportGUIexeListItem = new UISwissTransportGUIexeListItem(this);
                }
                return this.mUISwissTransportGUIexeListItem;
            }
        }
        
        public UIKopfzeileList UIKopfzeileList
        {
            get
            {
                if ((this.mUIKopfzeileList == null))
                {
                    this.mUIKopfzeileList = new UIKopfzeileList(this);
                }
                return this.mUIKopfzeileList;
            }
        }
        #endregion
        
        #region Fields
        private UISwissTransportGUIexeListItem mUISwissTransportGUIexeListItem;
        
        private UIKopfzeileList mUIKopfzeileList;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISwissTransportGUIexeListItem : WinListItem
    {
        
        public UISwissTransportGUIexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SwissTransportGUI.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIKopfzeileList : WinList
    {
        
        public UIKopfzeileList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinList.PropertyNames.Name] = "Kopfzeile";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinSplitButton UIÄnderungsdatumSplitButton
        {
            get
            {
                if ((this.mUIÄnderungsdatumSplitButton == null))
                {
                    this.mUIÄnderungsdatumSplitButton = new WinSplitButton(this);
                    #region Suchkriterien
                    this.mUIÄnderungsdatumSplitButton.SearchProperties[WinButton.PropertyNames.Name] = "Änderungsdatum";
                    this.mUIÄnderungsdatumSplitButton.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIÄnderungsdatumSplitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinSplitButton mUIÄnderungsdatumSplitButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIValidationcorrectWindow : WinWindow
    {
        
        public UIValidationcorrectWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Validation correct";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Static";
            this.WindowTitles.Add("Validation correct");
            #endregion
        }
        
        #region Properties
        public WinText UIValidationcorrectText
        {
            get
            {
                if ((this.mUIValidationcorrectText == null))
                {
                    this.mUIValidationcorrectText = new WinText(this);
                    #region Suchkriterien
                    this.mUIValidationcorrectText.SearchProperties[WinText.PropertyNames.Name] = "Validation correct";
                    this.mUIValidationcorrectText.WindowTitles.Add("Validation correct");
                    #endregion
                }
                return this.mUIValidationcorrectText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIValidationcorrectText;
        #endregion
    }
}
