// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITesting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// meggenhuobluzernbahnhof - Verwenden Sie "meggenhuobluzernbahnhofParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void meggenhuobluzernbahnhof()
        {
            #region Variable Declarations
            WinTreeItem uITransportapiTreeItem = this.UIExplorerWindow.UIStrukturansichtWindow.UISchnellzugriffTreeItem.UITransportapiTreeItem;
            WinListItem uIFertigesProgrammListItem = this.UIExplorerWindow.UIItemWindow.UIElementansichtList.UIFertigesProgrammListItem;
            WinButton uIZurückzuTransportapiButton = this.UIExplorerWindow.UINavigationsschaltfläToolBar.UIZurückzuTransportapiButton;
            WinTreeItem uIDieserPCTreeItem = this.UIExplorerWindow.UIStrukturansichtWindow.UIDesktopTreeItem.UIDieserPCTreeItem;
            WinEdit uIVerfügbarerSpeicherpEdit = this.UIExplorerWindow.UIItemWindow.UIWindowsCListItem.UIVerfügbarerSpeicherpEdit;
            WinEdit uINameEdit = this.UIExplorerWindow.UIItemWindow1.UIProgrammex86ListItem.UINameEdit;
            WinEdit uINameEdit1 = this.UIExplorerWindow.UIItemWindow2.UIJoëlTheilerListItem.UINameEdit;
            WinEdit uINameEdit2 = this.UIExplorerWindow.UIItemWindow3.UISetupSBBAPPListItem.UINameEdit;
            WinEdit uINameEdit3 = this.UIExplorerWindow.UIItemWindow4.UISwissTransportGUIexeListItem.UINameEdit;
            WinComboBox uICb_startComboBox = this.UITransportAppWindow.UICb_startWindow.UICb_startComboBox;
            WinButton uIStationsuchenButton = this.UITransportAppWindow.UIStationsuchenWindow.UIStationsuchenButton;
            WinComboBox uIBittegebenSieIhreStaComboBox = this.UITransportAppWindow.UICb_endWindow.UIBittegebenSieIhreStaComboBox;
            WinEdit uIItemEdit = this.UITransportAppWindow.UIItemWindow.UIItemEdit;
            WinWindow uIButton1Window = this.UITransportAppWindow.UITransportAppClient.UIButton1Window;
            #endregion

            // Klicken "Schnellzugriff" -> "Transportapi" Baumelement
            Mouse.Click(uITransportapiTreeItem, new Point(40, 10));

            // Doppelklicken "Fertiges Programm" Listenelement
            Mouse.DoubleClick(uIFertigesProgrammListItem, new Point(53, 84));

            // Klicken "Zurück zu Transportapi (Alt + Pfeil nach links)" Schaltfläche
            Mouse.Click(uIZurückzuTransportapiButton, new Point(19, 19));

            // Klicken "Desktop" -> "Dieser PC" Baumelement
            Mouse.Click(uIDieserPCTreeItem, new Point(52, 2));

            // Doppelklicken "Verfügbarer Speicherplatz" Textfeld
            Mouse.DoubleClick(uIVerfügbarerSpeicherpEdit, new Point(24, 0));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(111, 16));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit1, new Point(85, 10));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit2, new Point(82, 11));

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit3, new Point(79, 8));

            // "huob" in "cb_start" Kombinationsfeld auswählen
            uICb_startComboBox.EditableItem = this.meggenhuobluzernbahnhofParams.UICb_startComboBoxEditableItem;

            // Klicken "&Station suchen" Schaltfläche
            Mouse.Click(uIStationsuchenButton, new Point(17, 12));

            // "luzern bahnhof" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
            uIBittegebenSieIhreStaComboBox.EditableItem = this.meggenhuobluzernbahnhofParams.UIBittegebenSieIhreStaComboBoxEditableItem;

            // Klicken Textfeld
            Mouse.Click(uIItemEdit, new Point(225, 55));

            // Klicken "button1" Fenster
            Mouse.Click(uIButton1Window, new Point(187, 103));
        }
        
        #region Properties
        public virtual meggenhuobluzernbahnhofParams meggenhuobluzernbahnhofParams
        {
            get
            {
                if ((this.mmeggenhuobluzernbahnhofParams == null))
                {
                    this.mmeggenhuobluzernbahnhofParams = new meggenhuobluzernbahnhofParams();
                }
                return this.mmeggenhuobluzernbahnhofParams;
            }
        }
        
        public UIExplorerWindow UIExplorerWindow
        {
            get
            {
                if ((this.mUIExplorerWindow == null))
                {
                    this.mUIExplorerWindow = new UIExplorerWindow();
                }
                return this.mUIExplorerWindow;
            }
        }
        
        public UITransportAppWindow UITransportAppWindow
        {
            get
            {
                if ((this.mUITransportAppWindow == null))
                {
                    this.mUITransportAppWindow = new UITransportAppWindow();
                }
                return this.mUITransportAppWindow;
            }
        }
        #endregion
        
        #region Fields
        private meggenhuobluzernbahnhofParams mmeggenhuobluzernbahnhofParams;
        
        private UIExplorerWindow mUIExplorerWindow;
        
        private UITransportAppWindow mUITransportAppWindow;
        #endregion
    }
    
    /// <summary>
    /// An "meggenhuobluzernbahnhof" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class meggenhuobluzernbahnhofParams
    {
        
        #region Fields
        /// <summary>
        /// "huob" in "cb_start" Kombinationsfeld auswählen
        /// </summary>
        public string UICb_startComboBoxEditableItem = "huob";
        
        /// <summary>
        /// "luzern bahnhof" in "Bitte geben Sie Ihre Startstation ein:" Kombinationsfeld auswählen
        /// </summary>
        public string UIBittegebenSieIhreStaComboBoxEditableItem = "luzern bahnhof";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIExplorerWindow : WinWindow
    {
        
        public UIExplorerWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Explorer";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Explorer");
            this.WindowTitles.Add("Transportapi");
            this.WindowTitles.Add("Fertiges Programm");
            this.WindowTitles.Add("Dieser PC");
            this.WindowTitles.Add("Windows (C:)");
            this.WindowTitles.Add("Programme (x86)");
            this.WindowTitles.Add("Joël Theiler");
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public UIStrukturansichtWindow UIStrukturansichtWindow
        {
            get
            {
                if ((this.mUIStrukturansichtWindow == null))
                {
                    this.mUIStrukturansichtWindow = new UIStrukturansichtWindow(this);
                }
                return this.mUIStrukturansichtWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UINavigationsschaltfläToolBar UINavigationsschaltfläToolBar
        {
            get
            {
                if ((this.mUINavigationsschaltfläToolBar == null))
                {
                    this.mUINavigationsschaltfläToolBar = new UINavigationsschaltfläToolBar(this);
                }
                return this.mUINavigationsschaltfläToolBar;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        
        public UIItemWindow4 UIItemWindow4
        {
            get
            {
                if ((this.mUIItemWindow4 == null))
                {
                    this.mUIItemWindow4 = new UIItemWindow4(this);
                }
                return this.mUIItemWindow4;
            }
        }
        #endregion
        
        #region Fields
        private UIStrukturansichtWindow mUIStrukturansichtWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UINavigationsschaltfläToolBar mUINavigationsschaltfläToolBar;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow3 mUIItemWindow3;
        
        private UIItemWindow4 mUIItemWindow4;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStrukturansichtWindow : WinWindow
    {
        
        public UIStrukturansichtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("Explorer");
            #endregion
        }
        
        #region Properties
        public UISchnellzugriffTreeItem UISchnellzugriffTreeItem
        {
            get
            {
                if ((this.mUISchnellzugriffTreeItem == null))
                {
                    this.mUISchnellzugriffTreeItem = new UISchnellzugriffTreeItem(this);
                }
                return this.mUISchnellzugriffTreeItem;
            }
        }
        
        public UIDesktopTreeItem UIDesktopTreeItem
        {
            get
            {
                if ((this.mUIDesktopTreeItem == null))
                {
                    this.mUIDesktopTreeItem = new UIDesktopTreeItem(this);
                }
                return this.mUIDesktopTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UISchnellzugriffTreeItem mUISchnellzugriffTreeItem;
        
        private UIDesktopTreeItem mUIDesktopTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISchnellzugriffTreeItem : WinTreeItem
    {
        
        public UISchnellzugriffTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Schnellzugriff";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("Explorer");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UITransportapiTreeItem
        {
            get
            {
                if ((this.mUITransportapiTreeItem == null))
                {
                    this.mUITransportapiTreeItem = new WinTreeItem(this);
                    #region Suchkriterien
                    this.mUITransportapiTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Transportapi";
                    this.mUITransportapiTreeItem.SearchProperties["Value"] = "1";
                    this.mUITransportapiTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUITransportapiTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUITransportapiTreeItem.WindowTitles.Add("Explorer");
                    #endregion
                }
                return this.mUITransportapiTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUITransportapiTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDesktopTreeItem : WinTreeItem
    {
        
        public UIDesktopTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Desktop";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("Explorer");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIDieserPCTreeItem
        {
            get
            {
                if ((this.mUIDieserPCTreeItem == null))
                {
                    this.mUIDieserPCTreeItem = new WinTreeItem(this);
                    #region Suchkriterien
                    this.mUIDieserPCTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Dieser PC";
                    this.mUIDieserPCTreeItem.SearchProperties["Value"] = "1";
                    this.mUIDieserPCTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIDieserPCTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIDieserPCTreeItem.WindowTitles.Add("Explorer");
                    #endregion
                }
                return this.mUIDieserPCTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIDieserPCTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Transportapi");
            this.WindowTitles.Add("Dieser PC");
            #endregion
        }
        
        #region Properties
        public UIElementansichtList UIElementansichtList
        {
            get
            {
                if ((this.mUIElementansichtList == null))
                {
                    this.mUIElementansichtList = new UIElementansichtList(this);
                }
                return this.mUIElementansichtList;
            }
        }
        
        public UIWindowsCListItem UIWindowsCListItem
        {
            get
            {
                if ((this.mUIWindowsCListItem == null))
                {
                    this.mUIWindowsCListItem = new UIWindowsCListItem(this);
                }
                return this.mUIWindowsCListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIElementansichtList mUIElementansichtList;
        
        private UIWindowsCListItem mUIWindowsCListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIElementansichtList : WinList
    {
        
        public UIElementansichtList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinList.PropertyNames.Name] = "Elementansicht";
            this.WindowTitles.Add("Transportapi");
            #endregion
        }
        
        #region Properties
        public WinListItem UIFertigesProgrammListItem
        {
            get
            {
                if ((this.mUIFertigesProgrammListItem == null))
                {
                    this.mUIFertigesProgrammListItem = new WinListItem(this);
                    #region Suchkriterien
                    this.mUIFertigesProgrammListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Fertiges Programm";
                    this.mUIFertigesProgrammListItem.WindowTitles.Add("Transportapi");
                    #endregion
                }
                return this.mUIFertigesProgrammListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIFertigesProgrammListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIWindowsCListItem : WinListItem
    {
        
        public UIWindowsCListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Windows (C:)";
            this.WindowTitles.Add("Dieser PC");
            #endregion
        }
        
        #region Properties
        public WinEdit UIVerfügbarerSpeicherpEdit
        {
            get
            {
                if ((this.mUIVerfügbarerSpeicherpEdit == null))
                {
                    this.mUIVerfügbarerSpeicherpEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUIVerfügbarerSpeicherpEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Verfügbarer Speicherplatz";
                    this.mUIVerfügbarerSpeicherpEdit.WindowTitles.Add("Dieser PC");
                    #endregion
                }
                return this.mUIVerfügbarerSpeicherpEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIVerfügbarerSpeicherpEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UINavigationsschaltfläToolBar : WinToolBar
    {
        
        public UINavigationsschaltfläToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Navigationsschaltflächen";
            this.WindowTitles.Add("Fertiges Programm");
            #endregion
        }
        
        #region Properties
        public WinButton UIZurückzuTransportapiButton
        {
            get
            {
                if ((this.mUIZurückzuTransportapiButton == null))
                {
                    this.mUIZurückzuTransportapiButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIZurückzuTransportapiButton.SearchProperties[WinButton.PropertyNames.Name] = "Zurück zu Transportapi (Alt + Pfeil nach links)";
                    this.mUIZurückzuTransportapiButton.WindowTitles.Add("Fertiges Programm");
                    #endregion
                }
                return this.mUIZurückzuTransportapiButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIZurückzuTransportapiButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Windows (C:)");
            #endregion
        }
        
        #region Properties
        public UIProgrammex86ListItem UIProgrammex86ListItem
        {
            get
            {
                if ((this.mUIProgrammex86ListItem == null))
                {
                    this.mUIProgrammex86ListItem = new UIProgrammex86ListItem(this);
                }
                return this.mUIProgrammex86ListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIProgrammex86ListItem mUIProgrammex86ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIProgrammex86ListItem : WinListItem
    {
        
        public UIProgrammex86ListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Programme (x86)";
            this.WindowTitles.Add("Windows (C:)");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Windows (C:)");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Programme (x86)");
            #endregion
        }
        
        #region Properties
        public UIJoëlTheilerListItem UIJoëlTheilerListItem
        {
            get
            {
                if ((this.mUIJoëlTheilerListItem == null))
                {
                    this.mUIJoëlTheilerListItem = new UIJoëlTheilerListItem(this);
                }
                return this.mUIJoëlTheilerListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIJoëlTheilerListItem mUIJoëlTheilerListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIJoëlTheilerListItem : WinListItem
    {
        
        public UIJoëlTheilerListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Joël Theiler";
            this.WindowTitles.Add("Programme (x86)");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Programme (x86)");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Joël Theiler");
            #endregion
        }
        
        #region Properties
        public UISetupSBBAPPListItem UISetupSBBAPPListItem
        {
            get
            {
                if ((this.mUISetupSBBAPPListItem == null))
                {
                    this.mUISetupSBBAPPListItem = new UISetupSBBAPPListItem(this);
                }
                return this.mUISetupSBBAPPListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISetupSBBAPPListItem mUISetupSBBAPPListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISetupSBBAPPListItem : WinListItem
    {
        
        public UISetupSBBAPPListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SetupSBBAPP";
            this.WindowTitles.Add("Joël Theiler");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Joël Theiler");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public UISwissTransportGUIexeListItem UISwissTransportGUIexeListItem
        {
            get
            {
                if ((this.mUISwissTransportGUIexeListItem == null))
                {
                    this.mUISwissTransportGUIexeListItem = new UISwissTransportGUIexeListItem(this);
                }
                return this.mUISwissTransportGUIexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISwissTransportGUIexeListItem mUISwissTransportGUIexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISwissTransportGUIexeListItem : WinListItem
    {
        
        public UISwissTransportGUIexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SwissTransportGUI.exe";
            this.WindowTitles.Add("SetupSBBAPP");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("SetupSBBAPP");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppWindow : WinWindow
    {
        
        public UITransportAppWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Transport App";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public UICb_startWindow UICb_startWindow
        {
            get
            {
                if ((this.mUICb_startWindow == null))
                {
                    this.mUICb_startWindow = new UICb_startWindow(this);
                }
                return this.mUICb_startWindow;
            }
        }
        
        public UIStationsuchenWindow UIStationsuchenWindow
        {
            get
            {
                if ((this.mUIStationsuchenWindow == null))
                {
                    this.mUIStationsuchenWindow = new UIStationsuchenWindow(this);
                }
                return this.mUIStationsuchenWindow;
            }
        }
        
        public UICb_endWindow UICb_endWindow
        {
            get
            {
                if ((this.mUICb_endWindow == null))
                {
                    this.mUICb_endWindow = new UICb_endWindow(this);
                }
                return this.mUICb_endWindow;
            }
        }
        
        public UIItemWindow5 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow5(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UITransportAppClient UITransportAppClient
        {
            get
            {
                if ((this.mUITransportAppClient == null))
                {
                    this.mUITransportAppClient = new UITransportAppClient(this);
                }
                return this.mUITransportAppClient;
            }
        }
        #endregion
        
        #region Fields
        private UICb_startWindow mUICb_startWindow;
        
        private UIStationsuchenWindow mUIStationsuchenWindow;
        
        private UICb_endWindow mUICb_endWindow;
        
        private UIItemWindow5 mUIItemWindow;
        
        private UITransportAppClient mUITransportAppClient;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_startWindow : WinWindow
    {
        
        public UICb_startWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_start";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_startComboBox
        {
            get
            {
                if ((this.mUICb_startComboBox == null))
                {
                    this.mUICb_startComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUICb_startComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUICb_startComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_startComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIStationsuchenWindow : WinWindow
    {
        
        public UIStationsuchenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_searchststation";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinButton UIStationsuchenButton
        {
            get
            {
                if ((this.mUIStationsuchenButton == null))
                {
                    this.mUIStationsuchenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIStationsuchenButton.SearchProperties[WinButton.PropertyNames.Name] = "Station suchen";
                    this.mUIStationsuchenButton.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIStationsuchenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStationsuchenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UICb_endWindow : WinWindow
    {
        
        public UICb_endWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_end";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBittegebenSieIhreStaComboBox
        {
            get
            {
                if ((this.mUIBittegebenSieIhreStaComboBox == null))
                {
                    this.mUIBittegebenSieIhreStaComboBox = new WinComboBox(this);
                    #region Suchkriterien
                    this.mUIBittegebenSieIhreStaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bitte geben Sie Ihre Startstation ein:";
                    this.mUIBittegebenSieIhreStaComboBox.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIBittegebenSieIhreStaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBittegebenSieIhreStaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUIItemEdit.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UITransportAppClient : WinClient
    {
        
        public UITransportAppClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Transport App";
            this.WindowTitles.Add("Transport App");
            #endregion
        }
        
        #region Properties
        public WinWindow UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new WinWindow(this);
                    #region Suchkriterien
                    this.mUIButton1Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIButton1Window.WindowTitles.Add("Transport App");
                    #endregion
                }
                return this.mUIButton1Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIButton1Window;
        #endregion
    }
}
